set_property SRC_FILE_INFO {cfile:D:/projects/FPGA/PVS332/Xilinx/Timing.xdc rfile:../Timing.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name AHB_UART1/u2/BaudL -source [get_ports CLK] -divide_by 196 [get_pins AHB_UART1/u2/BaudOutL_reg/Q]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name AHB_UART1/u2/BaudOut_reg_0 -source [get_ports CLK] -divide_by 16 [get_pins AHB_UART1/u2/BaudOut_reg/Q]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name AHB_UART1/u3/TINT -source [get_pins AHB_UART1/u2/BaudOutL_reg/Q] -divide_by 1 [get_pins AHB_UART1/u3/TINT_reg/Q]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name AHB_UART1/u4/RINT -source [get_pins AHB_UART1/u2/BaudOut_reg/Q] -divide_by 1 [get_pins AHB_UART1/u4/INT_reg/Q]
