# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/projects/FPGA/PVS332/Xilinx/.Xil/Vivado-10052-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s15ftgb196-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog {
      D:/projects/FPGA/PVS332/Xilinx/.Xil/Vivado-10052-PC/realtime/BOOTROM_stub.v
      D:/projects/FPGA/PVS332/Xilinx/.Xil/Vivado-10052-PC/realtime/BLKRAM8_stub.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AFIO32.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_CCREG.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_DUMMY.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_GPIOC.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_OCRAM.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_ROM.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_UART.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/BaudGen.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/PERI_DECODE.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/PERI_MUX.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/SyncFIFO.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/UART_Rx.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/UART_Tx.v
      D:/projects/FPGA/PVS332/RTL/CPU/ahb.v
      D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_decoder.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/ahb_is62.v
      D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_mux_s2m.v
      D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_reset_ctrl.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/ahb_spi_v0.v
      D:/projects/FPGA/PVS332/RTL/CPU/alu.v
      D:/projects/FPGA/PVS332/RTL/CPU/au.v
      D:/projects/FPGA/PVS332/RTL/CPU/biu.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/clk_ctrl.v
      D:/projects/FPGA/PVS332/RTL/CPU/csr.v
      D:/projects/FPGA/PVS332/RTL/CPU/csr_gpr_iu.v
      D:/projects/FPGA/PVS332/RTL/CPU/exce_chk.v
      D:/projects/FPGA/PVS332/RTL/CPU/exu.v
      D:/projects/FPGA/PVS332/RTL/CPU/ins_dec.v
      D:/projects/FPGA/PVS332/RTL/CPU/int_ctrl.v
      D:/projects/FPGA/PVS332/RTL/CPU/mmu.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/pcod16s4.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/plic_cell.v
      D:/projects/FPGA/PVS332/RTL/CPU/prv332sv0.v
      D:/projects/FPGA/PVS332/RTL/Peripherals/spi_module.v
      D:/projects/FPGA/PVS332/RTL/TOP/PRV332_SoC.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top PRV332_SoC
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/projects/FPGA/PVS332/Xilinx/.Xil/Vivado-10052-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
