# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param synth.incrementalSynthesisCache C:/Users/USER/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13172-PC/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/projects/FPGA/PVS332/Xilinx/PVS332.cache/wt [current_project]
set_property parent.project_path D:/projects/FPGA/PVS332/Xilinx/PVS332.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/projects/FPGA/PVS332/Xilinx/PVS332.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/spi.coe
read_verilog -library xil_defaultlib {
  D:/projects/FPGA/PVS332/RTL/Peripherals/AFIO32.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_CCREG.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_DUMMY.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_GPIOC.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_OCRAM.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_ROM.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/AHB_UART.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/BaudGen.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/PERI_DECODE.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/PERI_MUX.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/SyncFIFO.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/UART_Rx.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/UART_Tx.v
  D:/projects/FPGA/PVS332/RTL/CPU/ahb.v
  D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_decoder.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/ahb_is62.v
  D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_mux_s2m.v
  D:/projects/FPGA/PVS332/RTL/AHB_Lite/ahb_reset_ctrl.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/ahb_spi_v0.v
  D:/projects/FPGA/PVS332/RTL/CPU/alu.v
  D:/projects/FPGA/PVS332/RTL/CPU/au.v
  D:/projects/FPGA/PVS332/RTL/CPU/biu.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/clk_ctrl.v
  D:/projects/FPGA/PVS332/RTL/CPU/csr.v
  D:/projects/FPGA/PVS332/RTL/CPU/csr_gpr_iu.v
  D:/projects/FPGA/PVS332/RTL/CPU/exce_chk.v
  D:/projects/FPGA/PVS332/RTL/CPU/exu.v
  D:/projects/FPGA/PVS332/RTL/CPU/ins_dec.v
  D:/projects/FPGA/PVS332/RTL/CPU/int_ctrl.v
  D:/projects/FPGA/PVS332/RTL/CPU/mmu.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/pcod16s4.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/plic_cell.v
  D:/projects/FPGA/PVS332/RTL/CPU/prv332sv0.v
  D:/projects/FPGA/PVS332/RTL/Peripherals/spi_module.v
  D:/projects/FPGA/PVS332/RTL/TOP/PRV332_SoC.v
}
read_ip -quiet D:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM.xci
set_property used_in_implementation false [get_files -all d:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM_ooc.xdc]

read_ip -quiet D:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BLKRAM8_1/BLKRAM8.xci
set_property used_in_implementation false [get_files -all d:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BLKRAM8_1/BLKRAM8_ooc.xdc]

read_ip -quiet d:/projects/FPGA/PVS332/Xilinx/PVS332.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/projects/FPGA/PVS332/Xilinx/PVS332.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/projects/FPGA/PVS332/Xilinx/PVS332.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/projects/FPGA/PVS332/Xilinx/PVS332.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/projects/FPGA/PVS332/Xilinx/Timing.xdc
set_property used_in_implementation false [get_files D:/projects/FPGA/PVS332/Xilinx/Timing.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PRV332_SoC -part xc7s15ftgb196-1 -bufg 100 -fanout_limit 15


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PRV332_SoC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PRV332_SoC_utilization_synth.rpt -pb PRV332_SoC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
