# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM.xci
# IP: The module: 'BOOTROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BOOTROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM.xci
# IP: The module: 'BOOTROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/FPGA/PVS332/Xilinx/Xilinx_IP/BOOTROM/BOOTROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BOOTROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
