/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Projects/FPGA/PVS332/Anlogic/al_ip/BOOTROM1.v
 ** Date	:	2019 10 20
 ** TD version	:	4.1.533
\************************************************************/

`timescale 1ns / 1ps

module BROM ( doa, addra, ocea, clka, rsta );

	output [31:0] doa;

	input  [14:0] addra;
	input  ocea;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.ADDR_WIDTH_A(15),
				.DATA_DEPTH_A(32768),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_B(15),
				.DATA_DEPTH_B(32768),
				.MODE("SP"),
				.REGMODE_A("OUTREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../BIN/BROM.MIF"),
				.FILL_ALL("NONE"))
			inst(
				.dia({32{1'b0}}),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb({15{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(ocea),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule